# -*- coding: utf-8 -*-
"""AgentsMistral.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10XRERsryxXHHmaI2DgJdM3vanHre0pxD

#Instalaciones y dependencias
"""

!pip install pandas langchain langchain-experimental tabulate langchain-ollama

"""#Importaciones"""

import pandas as pd
import langchain

print("Pandas version:", pd.__version__)
print("LangChain version:", langchain.__version__)
print("✅ Todo instalado correctamente")

"""#Config de API key"""

from google.colab import userdata
import os

os.environ["MISTRAL_API_KEY"] = userdata.get("MISTRAL_API_KEY")
print("✅ API Key cargada correctamente")

# hN52sFFQiQkRTjUIoZjQM8H5sYJPv4J4

"""# Instalar mistral y Testing de conexion"""

!pip install langchain-mistralai

from langchain_mistralai import ChatMistralAI

llm = ChatMistralAI(
    model="mistral-small-latest",
    temperature=0
)

respuesta = llm.invoke("Respondé solo esto: ¿estás funcionando?")
print(respuesta.content)

"""#Carga del dataset

"""

import pandas as pd

df = pd.read_csv("sales_data_sample.csv", encoding="latin-1")

print(f"Filas: {df.shape[0]}")
print(f"Columnas: {df.shape[1]}")
print("\nNombres de columnas:")
print(df.columns.tolist())

df.head()

"""# Normalizacion del dataset"""

# Normalizar nombres de columnas
df.columns = df.columns.str.strip().str.upper().str.replace(" ", "_")

# Verificar valores nulos
print("Valores nulos por columna:")
print(df.isnull().sum())

#tipos de datos en df
print("Tipos de datos por columna:")
print(df.dtypes)

# estadisticas generales
print("Estadísticas de columnas numéricas:")
df.describe()

# Guardar el CSV limpio
df.to_csv("ventas.csv", index=False)
print("\n✅ Dataset limpio guardado como ventas.csv")

print(f"Filas: {df.shape[0]}")
print(f"Columnas: {df.shape[1]}")

"""# Creacion del agente"""

from langchain_mistralai import ChatMistralAI
from langchain_experimental.agents.agent_toolkits import create_pandas_dataframe_agent

# LLM
llm = ChatMistralAI(
    model="mistral-small-latest",
    temperature=0
)

# Contexto del dataset
prefix = """
Sos un analista de datos experto en ventas.
Trabajás con un DataFrame que tiene estas columnas:
- ORDERNUMBER: número de orden
- QUANTITYORDERED: cantidad de productos pedidos
- PRICEEACH: precio unitario
- SALES: total de la venta
- ORDERDATE: fecha del pedido
- STATUS: estado del pedido (Shipped, Cancelled, Pending, On Hold)
- PRODUCTLINE: línea de producto
- CUSTOMERNAME: nombre del cliente
- CITY: ciudad
- COUNTRY: país
- DEALSIZE: tamaño del deal (Small, Medium, Large)

Respondé siempre en español, de forma clara y concisa.
Si no podés responder, decilo claramente.
"""

# Crear el agente
agent = create_pandas_dataframe_agent(
    llm,
    df,
    prefix=prefix,
    verbose=True,
    allow_dangerous_code=True,
)

print("✅ Agente creado correctamente")

respuesta = agent.invoke("¿Cuántas filas tiene el dataset?")
print("\n🤖", respuesta["output"])

respuesta = agent.invoke("Cuál fue al año que mayor venta hubo?")
print("\n🤖", respuesta["output"])

respuesta = agent.invoke("Cuál fue el año con menor venta?")
print("\n🤖", respuesta["output"])

respuesta = agent.invoke("¿En base al promedio de ventas, se puede decir que la empresa tiene rentabilidad?")
print("\n🤖", respuesta["output"])

respuesta = agent.invoke("¿Cuál fue el país donde mayor venta hubo?")
print("\n🤖", respuesta["output"])