# -*- coding: utf-8 -*-
"""diabetes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dAbtNQWUL3mS8n7R8Dtfnxe_4PKRWzEK
"""

# ====================================
# CELDA 1 — Librerías
# ====================================

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (accuracy_score, confusion_matrix,
                             classification_report, ConfusionMatrixDisplay, roc_auc_score,
                              f1_score, precision_score, recall_score)
from sklearn.preprocessing import StandardScaler
from matplotlib.patches import Patch

from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB

"""#Creacion del dataset"""

# ====================================
# CELDA 2 — Crear dataset simulado
# ====================================

np.random.seed(42)
n = 300

edad  = np.random.randint(20, 70, n)
peso  = np.random.randint(50, 120, n)
imc   = np.round(peso / ((np.random.uniform(1.50, 1.85, n)) ** 2), 1)

# Regla: riesgo si IMC > 27 Y edad > 40, o IMC > 30 solo
riesgo = (((imc > 27) & (edad > 40)) | (imc > 30)).astype(int)

# Agregar ruido realista
ruido  = np.random.rand(n) < 0.07
riesgo = np.where(ruido, 1 - riesgo, riesgo)

df = pd.DataFrame({
    'edad':   edad,
    'peso':   peso,
    'imc':    imc,
    'riesgo': riesgo
})

df['diagnostico'] = df['riesgo'].map({1: 'Con riesgo', 0: 'Sin riesgo'})

print(df.head(10))
print(f"\nDistribución:\n{df['diagnostico'].value_counts()}")

"""#Exploracion visual"""

# ====================================
# CELDA 3 — Exploración visual
# ====================================

fig, axes = plt.subplots(1, 3, figsize=(18, 5))
fig.suptitle('Exploración del dataset — Riesgo de Diabetes',
             fontsize=15, fontweight='bold')

colores_scatter = df['riesgo'].map({1: '#e74c3c', 0: '#2ecc71'})

# Gráfico 1: IMC vs Edad
axes[0].scatter(df['edad'], df['imc'],
                c=colores_scatter, alpha=0.7,
                edgecolors='black', linewidth=0.5)
axes[0].set_xlabel('Edad', fontsize=12)
axes[0].set_ylabel('IMC', fontsize=12)
axes[0].set_title('IMC vs Edad', fontsize=13)
axes[0].legend(handles=[
    Patch(color='#e74c3c', label='Con riesgo'),
    Patch(color='#2ecc71', label='Sin riesgo')
])
axes[0].spines['top'].set_visible(False)
axes[0].spines['right'].set_visible(False)

# Gráfico 2: Distribución IMC por diagnóstico
df.boxplot(column='imc', by='diagnostico', ax=axes[1],
           patch_artist=True,
           boxprops=dict(facecolor='#3498db', color='black'),
           medianprops=dict(color='black', linewidth=2))
axes[1].set_title('IMC por diagnóstico', fontsize=13)
axes[1].set_xlabel('')
axes[1].set_ylabel('IMC', fontsize=12)
plt.sca(axes[1])
plt.title('IMC por diagnóstico', fontsize=13)
plt.suptitle('')
axes[1].spines['top'].set_visible(False)
axes[1].spines['right'].set_visible(False)

# Gráfico 3: Conteo
df['diagnostico'].value_counts().plot(
    kind='bar', ax=axes[2],
    color=['#e74c3c', '#2ecc71'],
    edgecolor='black', width=0.5
)
axes[2].set_title('Cantidad por diagnóstico', fontsize=13)
axes[2].set_xlabel('')
axes[2].set_ylabel('Cantidad', fontsize=12)
axes[2].tick_params(axis='x', rotation=0)
for p in axes[2].patches:
    axes[2].text(p.get_x() + p.get_width() / 2,
                 p.get_height() + 1,
                 str(int(p.get_height())),
                 ha='center', fontweight='bold')
axes[2].spines['top'].set_visible(False)
axes[2].spines['right'].set_visible(False)

plt.tight_layout()
plt.show()

"""#Divison de datos y entrenamiento de modelo"""

# ====================================
# CELDA 4 — Entrenar el modelo
# ====================================

X = df[['edad', 'peso', 'imc']]
y = df['riesgo']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

scaler  = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test  = scaler.transform(X_test)

modelo = LogisticRegression()
modelo.fit(X_train, y_train)

y_pred = modelo.predict(X_test)

print(f"Precisión del modelo: {accuracy_score(y_test, y_pred) * 100:.1f}%")
print()
print("Reporte de clasificación:")
print(classification_report(y_test, y_pred,
      target_names=['Sin riesgo', 'Con riesgo']))

"""#Matriz de confusion"""

# ====================================
# CELDA 5 — Matriz de confusión
# ====================================

fig, ax = plt.subplots(figsize=(6, 5))

cm   = confusion_matrix(y_test, y_pred)
disp = ConfusionMatrixDisplay(confusion_matrix=cm,
                               display_labels=['Sin riesgo', 'Con riesgo'])
disp.plot(ax=ax, colorbar=False, cmap='Reds')

ax.set_title('Matriz de confusión — Diagnóstico de Diabetes',
             fontsize=13, fontweight='bold', pad=15)
plt.tight_layout()
plt.show()

"""#Importancia de variables"""

# ====================================
# CELDA 6 — Importancia de variables
# ====================================

coeficientes = pd.DataFrame({
    'variable':    ['Edad', 'Peso', 'IMC'],
    'coeficiente': np.abs(modelo.coef_[0])
}).sort_values('coeficiente', ascending=True)

fig, ax = plt.subplots(figsize=(8, 4))

bars = ax.barh(coeficientes['variable'],
               coeficientes['coeficiente'],
               color='#3498db', edgecolor='black', linewidth=0.8)

for bar, val in zip(bars, coeficientes['coeficiente']):
    ax.text(bar.get_width() + 0.005,
            bar.get_y() + bar.get_height() / 2,
            f'{val:.3f}', va='center',
            fontsize=11, fontweight='bold')

ax.set_title('Importancia de variables en el modelo',
             fontsize=13, fontweight='bold', pad=15)
ax.set_xlabel('Coeficiente (valor absoluto)', fontsize=12)
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)

plt.tight_layout()
plt.show()

# ====================================
# CELDA 7 — Frontera de decisión (IMC vs Edad)
# ====================================

edad_range = np.linspace(20, 70, 300)
imc_range  = np.linspace(15, 45, 300)
xx1, xx2   = np.meshgrid(edad_range, imc_range)

peso_medio = df['peso'].mean()
grid       = np.c_[xx1.ravel(),
                   np.full(xx1.ravel().shape, peso_medio),
                   xx2.ravel()]

grid_scaled = scaler.transform(grid)
Z           = modelo.predict(grid_scaled).reshape(xx1.shape)

fig, ax = plt.subplots(figsize=(9, 6))

ax.contourf(xx1, xx2, Z, alpha=0.25,
            colors=['#2ecc71', '#e74c3c'])
ax.contour(xx1, xx2, Z, colors='black',
           linewidths=1.5, linestyles='--')

ax.scatter(df['edad'], df['imc'],
           c=df['riesgo'].map({1: '#e74c3c', 0: '#2ecc71'}),
           edgecolors='black', linewidth=0.5, alpha=0.8)

ax.set_xlabel('Edad', fontsize=12)
ax.set_ylabel('IMC', fontsize=12)
ax.set_title('Frontera de decisión — IMC vs Edad',
             fontsize=13, fontweight='bold')
ax.legend(handles=[
    Patch(color='#e74c3c', label='Con riesgo'),
    Patch(color='#2ecc71', label='Sin riesgo')
])

plt.tight_layout()
plt.show()

"""#Prediccion de nuevos casos"""

# ====================================
# CELDA 8 — Predecir casos nuevos
# ====================================

print("=== Predicción de pacientes nuevos ===\n")

pacientes = pd.DataFrame({
    'edad': [55, 28, 45, 32],
    'peso': [95, 60, 88, 70],
    'imc':  [32.5, 21.3, 29.8, 24.1]
})

pacientes_scaled = scaler.transform(pacientes)
predicciones     = modelo.predict(pacientes_scaled)
probabilidad     = modelo.predict_proba(pacientes_scaled)

for i, (_, row) in enumerate(pacientes.iterrows()):
    resultado = 'CON RIESGO 🔴' if predicciones[i] == 1 else 'SIN RIESGO 🟢'
    prob      = probabilidad[i][predicciones[i]] * 100
    print(f"Paciente {i+1}: {int(row['edad'])} años, "
          f"{int(row['peso'])}kg, IMC {row['imc']}  →  "
          f"{resultado}  (confianza: {prob:.1f}%)")

# ====================================
# CELDA 9 — Curva ROC AUC
# ====================================

from sklearn.metrics import roc_curve, roc_auc_score

# Probabilidad de pertenecer a la clase positiva (con riesgo)
y_prob = modelo.predict_proba(X_test)[:, 1]

# Calcular curva ROC
fpr, tpr, umbrales = roc_curve(y_test, y_prob)
auc_score          = roc_auc_score(y_test, y_prob)

# ── Gráfico ───────────────────────────────────────────────────────────────────
fig, ax = plt.subplots(figsize=(8, 6))

# Curva del modelo
ax.plot(fpr, tpr, color='#e74c3c', linewidth=2.5,
        label=f'Regresión Logística (AUC = {auc_score:.3f})')

# Línea base (modelo aleatorio)
ax.plot([0, 1], [0, 1], color='gray', linewidth=1.5,
        linestyle='--', label='Modelo aleatorio (AUC = 0.500)')

# Área bajo la curva
ax.fill_between(fpr, tpr, alpha=0.15, color='#e74c3c')

# Punto óptimo (menor distancia al esquina superior izquierda)
distancias    = np.sqrt((fpr ** 2) + ((1 - tpr) ** 2))
idx_optimo    = np.argmin(distancias)
ax.scatter(fpr[idx_optimo], tpr[idx_optimo],
           color='#c0392b', s=100, zorder=5,
           label=f'Umbral óptimo = {umbrales[idx_optimo]:.2f}')

ax.set_xlabel('Tasa de Falsos Positivos (1 - Especificidad)', fontsize=12)
ax.set_ylabel('Tasa de Verdaderos Positivos (Sensibilidad)', fontsize=12)
ax.set_title('Curva ROC — Diagnóstico de Riesgo de Diabetes',
             fontsize=13, fontweight='bold', pad=15)
ax.legend(fontsize=11)
ax.set_xlim([0, 1])
ax.set_ylim([0, 1.02])
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)
ax.grid(alpha=0.3)

plt.tight_layout()
plt.savefig('curva_roc.png', dpi=300, bbox_inches='tight')
plt.show()

print(f"AUC Score: {auc_score:.3f}")
print(f"Umbral óptimo: {umbrales[idx_optimo]:.3f}")
print(f"  Sensibilidad en umbral óptimo: {tpr[idx_optimo]:.3f}")
print(f"  Especificidad en umbral óptimo: {1 - fpr[idx_optimo]:.3f}")

"""#Evaluacion por modelos"""

# ====================================
# CELDA 10 — Comparación de modelos
# ====================================

from sklearn.svm import SVC
# ── Definir modelos ───────────────────────────────────────────────────────────
modelos = {
    'Regresión Logística':  LogisticRegression(random_state=42),
    'Árbol de Decisión':    DecisionTreeClassifier(random_state=42),
    'Random Forest':        RandomForestClassifier(random_state=42),
    'Gradient Boosting':    GradientBoostingClassifier(random_state=42),
    'SVM':                  SVC(probability=True, random_state=42),
    'KNN':                  KNeighborsClassifier(),
    'Naive Bayes':          GaussianNB(),
}

# ── Evaluar cada modelo ───────────────────────────────────────────────────────
resultados = []

for nombre, modelo_eval in modelos.items():
    modelo_eval.fit(X_train, y_train)
    y_pred_eval = modelo_eval.predict(X_test)
    y_prob_eval = modelo_eval.predict_proba(X_test)[:, 1]

    resultados.append({
        'Modelo':       nombre,
        'Accuracy':     accuracy_score(y_test, y_pred_eval),
        'AUC':          roc_auc_score(y_test, y_prob_eval),
        'F1-Score':     f1_score(y_test, y_pred_eval),
        'Precisión':    precision_score(y_test, y_pred_eval),
        'Sensibilidad': recall_score(y_test, y_pred_eval),
    })

df_resultados = pd.DataFrame(resultados).sort_values('AUC', ascending=False)
df_resultados = df_resultados.reset_index(drop=True)
df_resultados.index += 1

# Redondear para mostrar
df_display = df_resultados.copy()
for col in ['Accuracy', 'AUC', 'F1-Score', 'Precisión', 'Sensibilidad']:
    df_display[col] = df_display[col].apply(lambda x: f'{x:.3f}')

print("=" * 75)
print("           COMPARACIÓN DE MODELOS — ordenado por AUC")
print("=" * 75)
print(df_display.to_string())
print("=" * 75)
print(f"\nMejor modelo por AUC: {df_resultados.iloc[0]['Modelo']} "
      f"({df_resultados.iloc[0]['AUC']:.3f})")

# ── Gráfico 1: Barras comparativas por métrica ────────────────────────────────
metricas = ['Accuracy', 'AUC', 'F1-Score', 'Precisión', 'Sensibilidad']
x        = np.arange(len(df_resultados))
ancho    = 0.15
colores  = ['#3498db', '#e74c3c', '#2ecc71', '#9b59b6', '#e67e22']

fig, ax = plt.subplots(figsize=(16, 6))

for i, (metrica, color) in enumerate(zip(metricas, colores)):
    bars = ax.bar(x + i * ancho,
                  df_resultados[metrica],
                  width=ancho, label=metrica,
                  color=color, edgecolor='black', linewidth=0.5)

ax.set_xticks(x + ancho * 2)
ax.set_xticklabels(df_resultados['Modelo'], fontsize=10, rotation=15, ha='right')
ax.set_ylim(0, 1.15)
ax.set_ylabel('Score', fontsize=12)
ax.set_title('Comparación de modelos por métrica',
             fontsize=14, fontweight='bold', pad=15)
ax.legend(fontsize=10, loc='upper right')
ax.axhline(y=0.9, color='gray', linestyle='--',
           linewidth=1, alpha=0.5, label='Umbral 0.90')
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)

plt.tight_layout()
plt.savefig('comparacion_modelos.png', dpi=300, bbox_inches='tight')
plt.show()

# ── Gráfico 2: Curvas ROC de todos los modelos ────────────────────────────────
from sklearn.metrics import roc_curve

colores_roc = ['#3498db', '#e74c3c', '#2ecc71',
               '#9b59b6', '#e67e22', '#1abc9c', '#e91e63']

fig, ax = plt.subplots(figsize=(9, 7))

for (nombre, modelo_eval), color in zip(modelos.items(), colores_roc):
    y_prob_roc = modelo_eval.predict_proba(X_test)[:, 1]
    fpr_m, tpr_m, _ = roc_curve(y_test, y_prob_roc)
    auc_m = roc_auc_score(y_test, y_prob_roc)
    ax.plot(fpr_m, tpr_m, color=color, linewidth=2,
            label=f'{nombre} (AUC = {auc_m:.3f})')

# Línea base
ax.plot([0, 1], [0, 1], color='gray', linewidth=1.5,
        linestyle='--', label='Modelo aleatorio (AUC = 0.500)')

ax.set_xlabel('Tasa de Falsos Positivos', fontsize=12)
ax.set_ylabel('Tasa de Verdaderos Positivos', fontsize=12)
ax.set_title('Curvas ROC — Comparación de todos los modelos',
             fontsize=13, fontweight='bold', pad=15)
ax.legend(fontsize=9, loc='lower right')
ax.set_xlim([0, 1])
ax.set_ylim([0, 1.02])
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)
ax.grid(alpha=0.3)

plt.tight_layout()
plt.savefig('curvas_roc_todos.png', dpi=300, bbox_inches='tight')
plt.show()

# ── Gráfico 3: Ranking por AUC ────────────────────────────────────────────────
fig, ax = plt.subplots(figsize=(10, 5))

colores_rank = ['#f1c40f' if i == 0 else
                '#95a5a6' if i == 1 else
                '#cd7f32' if i == 2 else
                '#3498db'
                for i in range(len(df_resultados))]

bars = ax.barh(df_resultados['Modelo'][::-1],
               df_resultados['AUC'][::-1],
               color=colores_rank[::-1],
               edgecolor='black', linewidth=0.8)

for bar, val in zip(bars, df_resultados['AUC'][::-1]):
    ax.text(bar.get_width() + 0.003,
            bar.get_y() + bar.get_height() / 2,
            f'{val:.3f}', va='center',
            fontsize=11, fontweight='bold')

ax.set_xlim(0, 1.12)
ax.axvline(x=0.9, color='red', linestyle='--',
           linewidth=1.2, alpha=0.6, label='Umbral excelente (0.90)')
ax.set_xlabel('AUC Score', fontsize=12)
ax.set_title('Ranking de modelos por AUC',
             fontsize=13, fontweight='bold', pad=15)
ax.legend(fontsize=10)
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)

plt.tight_layout()
plt.savefig('ranking_auc.png', dpi=300, bbox_inches='tight')
plt.show()